# Generated by Django 5.1.4 on 2024-12-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currensy_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exchange', models.Field()),
                ('Currency', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rewiew_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('avatar', models.URLField()),
                ('grade', models.Field()),
            ],
        ),
        migrations.CreateModel(
            name='VK_clip_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link', models.CharField(max_length=255)),
                ('Prewiew', models.CharField(max_length=255)),
            ],
        ),
    ]
