# Generated by Django 3.2.25 on 2025-01-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TomikoApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currensy_model',
        ),
        migrations.DeleteModel(
            name='Rewiew_Model',
        ),
        migrations.DeleteModel(
            name='VK_clip_model',
        ),
    ]
