# Generated by Django 5.1.4 on 2024-12-18 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brands",
            options={
                "managed": False,
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренды",
            },
        ),
        migrations.AlterModelOptions(
            name="cars",
            options={
                "managed": False,
                "verbose_name": "Автомобиль",
                "verbose_name_plural": "Автомобили",
            },
        ),
    ]
